name: 'Build and deploy'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: 'Cache Node dependencies'
      uses: 'actions/cache@v4'
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm ci

    - name: Run build task
      run: npm run build --if-present
